package yazilimTestiOdev;

public class TestStrings {

	public static final String testKodOgrenci="package pkt;\r\n"
			+ "\r\n"
			+ "public class Ogrenci {\r\n"
			+ "	private String isim;\r\n"
			+ "	private String no;\r\n"
			+ "	private int yas;\r\n"
			+ "	\r\n"
			+ "	public Ogrenci(String isim, String no, int yas) {\r\n"
			+ "		if(yas<50)this.isim = isim;\r\n"
			+ "		else this.isim = \"x+y/2++yas\";\r\n"
			+ "		this.no = no;\r\n"
			+ "		this.yas = yas;\r\n"
			+ "	}\r\n"
			+ "	public int yasUret() {\r\n"
			+ "		return yas + ++yas * yas--;\r\n"
			+ "	}\r\n"
			+ "	// yas + ++yas * yas--\r\n"
			+ "	public double ortalama(double not) { return not/(not/2);} \r\n"
			+ "	public boolean gectimi(double not) {\r\n"
			+ "		return not >= 50;\r\n"
			+ "	}\r\n"
			+ "	/**\r\n"
			+ "	 * +\r\n"
			+ "		++\r\n"
			+ "		-\r\n"
			+ "		--\r\n"
			+ "		*\r\n"
			+ "		/\r\n"
			+ "		%\r\n"
			+ "		&\r\n"
			+ "		|\r\n"
			+ "		^\r\n"
			+ "		=\r\n"
			+ "		+=\r\n"
			+ "		-=\r\n"
			+ "		/=\r\n"
			+ "		*=\r\n"
			+ "		%=\r\n"
			+ "		&=\r\n"
			+ "		|=\r\n"
			+ "		^=\r\n"
			+ "	 */// ++++"
			+"\n"
			+ "	public boolean sagliklimi(int x,int y) {\r\n"
			+ "		return (x>y && y>50)  || !(x<100);\r\n"
			+ "	}\r\n"
			+ "}";
	public static final String yorumsuzTestKodOgrenci="package pkt;public class Ogrenci {	private String isim;	private String no;	private int yas;		public Ogrenci(String isim, String no, int yas) {		if(yas<50)this.isim = isim;		else this.isim = \"x+y/2++yas\";		this.no = no;		this.yas = yas;	}	public int yasUret() {		return yas + ++yas * yas--;	}	public double ortalama(double not) { return not/(not/2);} 	public boolean gectimi(double not) {		return not >= 50;	}	public boolean sagliklimi(int x,int y) {		return (x>y && y>50)  || !(x<100);	}}";
	public static final String testKodDeneme="package odev;\r\n"
			+ "public class Deneme {\r\n"
			+ "public int x;\r\n"
			+ "public int y;\r\n"
			+ "public Deneme(int x,int y) {\r\n"
			+ "this.x = x;\r\n"
			+ "this.y = y;\r\n"
			+ "}\r\n"
			+ "/*\r\n"
			+ "*\r\n"
			+ "* x*x + y*y // işlemi x > 0 ve y > 0\r\n"
			+ "*/\r\n"
			+ "public int x2y2() {\r\n"
			+ "return x * x + y * y;\r\n"
			+ "}\r\n"
			+ "/*\r\n"
			+ "* Karakök işlemi yapan fonksiyon\r\n"
			+ "* karakok(x*x + y*y)\r\n"
			+ "*/\r\n"
			+ "public double karakok() {\r\n"
			+ "return Math.sqrt((double)x2y2());\r\n"
			+ "}\r\n"
			+ "// log2(x/++y)\r\n"
			+ "public double log2() {\r\n"
			+ "++y;\r\n"
			+ "return Math.log(((double)x)/y);\r\n"
			+ "}\r\n"
			+ "@Override\r\n"
			+ "public boolean equals(Object obj) {\r\n"
			+ "if(obj != null && obj instanceof Deneme) {\r\n"
			+ "return ((Deneme)obj).x == this.x && ((Deneme)obj).y == this.y;\r\n"
			+ "}\r\n"
			+ "return false;\r\n"
			+ "}\r\n"
			+ "}";
	public static final String yorumsuzTestKodDeneme="package odev;public class Deneme {public int x;public int y;public Deneme(int x,int y) {this.x = x;this.y = y;}public int x2y2() {return x * x + y * y;}public double karakok() {return Math.sqrt((double)x2y2());}public double log2() {++y;return Math.log(((double)x)/y);}@Overridepublic boolean equals(Object obj) {if(obj != null && obj instanceof Deneme) {return ((Deneme)obj).x == this.x && ((Deneme)obj).y == this.y;}return false;}}";
	public static final String testKodEsittir="public class Example {\r\n"
			+ "  public static void main(String[] args) {\r\n"
			+ "    int x = 5;\r\n"
			+ "    int y = 5;\r\n"
			+ "    String s1 = \"hello\";\r\n"
			+ "    String s2 = \"hello\";\r\n"
			+ "    String s3 = new String(\"hello\");\r\n"
			+ "    \r\n"
			+ "    if (x == y) {\r\n"
			+ "      System.out.println(\"x is equal to y\");\r\n"
			+ "    }\r\n"
			+ "    \r\n"
			+ "    if (s1 == s2) {\r\n"
			+ "      System.out.println(\"s1 is the same object as s2\");\r\n"
			+ "    }\r\n"
			+ "    \r\n"
			+ "    if (s1 == s3) {\r\n"
			+ "      System.out.println(\"s1 is the same object as s3\");\r\n"
			+ "    } else {\r\n"
			+ "      System.out.println(\"s1 is not the same object as s3\");\r\n"
			+ "    }\r\n"
			+ "    \r\n"
			+ "    Object obj1 = new Object();\r\n"
			+ "    Object obj2 = new Object();\r\n"
			+ "    \r\n"
			+ "    if (obj1 == obj2) {\r\n"
			+ "      System.out.println(\"obj1 is the same object as obj2\");\r\n"
			+ "    } else {\r\n"
			+ "      System.out.println(\"obj1 is not the same object as obj2\");\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "}";
		public static final String yorumsuzTestKodEsittir="public class Example {  public static void main(String[] args) {    int x = 5;    int y = 5;    String s1 = \"hello\";    String s2 = \"hello\";    String s3 = new String(\"hello\");        if (x == y) {      System.out.println(\"x is equal to y\");    }        if (s1 == s2) {      System.out.println(\"s1 is the same object as s2\");    }        if (s1 == s3) {      System.out.println(\"s1 is the same object as s3\");    } else {      System.out.println(\"s1 is not the same object as s3\");    }        Object obj1 = new Object();    Object obj2 = new Object();        if (obj1 == obj2) {      System.out.println(\"obj1 is the same object as obj2\");    } else {      System.out.println(\"obj1 is not the same object as obj2\");    }  }}";
		public static final String mantiksalUnlemTest="public class OperatorExample {\r\n"
				+ "    public static void main(String[] args) {\r\n"
				+ "        int a = 10;\r\n"
				+ "        int b = 5;\r\n"
				+ "        int c = 20;\r\n"
				+ "\r\n if (a != b)"
				+ "        int result1 = (a + b) * c;\r\n"
				+ "\r\n"
				+ "        int result2 = a % b;\r\n"
				+ "\r\n if (a != b)"
				+ "        boolean result3 = (a > b) && (c > a);\r\n"
				+ "\r\n"
				+ "        boolean result4 = (a < b) || (c > a);\r\n"
				+ "\r\n"
				+ "        boolean result5 = !(a > b);\r\n"
				+ "        System.out.println(\"!(a > b) = \" + result5);\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "";
		public static final String mantiksalUnlemTestYorumsuz="public class OperatorExample {    public static void main(String[] args) {        int a = 10;        int b = 5;        int c = 20;        int result1 = (a + b) * c;              int result2 = a % b;              boolean result3 = (a > b) && (c > a);                boolean result4 = (a < b) || (c > a);               boolean result5 = !(a > b);           }}";
}
